#[derive(Debug, PartialEq, Eq, Hash)]
pub enum Command {
    Agent,
    Add,
    Install,
    Run,
    Unkown,
    Frozen,
    Global,
    Upgrade,
    Uninstall,
    GlobalUninstall,
    Execute,
    UpgradeInteractive,
    IgnoredCommand,
    GitClone,
    GitPull,
    GitPush,
    GitLog,
    RemoveNodeModules,
    RemoveLockFile,
    PkgInfo,
}
